2023-09-15 20:13:33,727 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:14:34,289 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:15:34,757 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:16:34,877 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:17:35,648 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:18:35,763 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:19:36,500 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:20:37,030 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:21:37,117 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:22:37,985 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:23:38,464 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:24:38,822 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:25:39,286 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:26:39,430 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:32:24,806 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:35:54,625 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:36:54,983 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:37:55,711 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:38:56,176 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-15 20:39:56,308 ERROR scheduler Exception in Enqueue Events for Site erp.visitouriran.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 100, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 27, in enqueue
    if self.is_event_due() or force:
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 51, in is_event_due
    return self.get_next_execution() <= (current_time or now_datetime())
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 77, in get_next_execution
    "All": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
TypeError: unsupported operand type(s) for //: 'str' and 'int'

2023-09-16 09:48:56,278 ERROR scheduler Exception in Enqueue Events for Site taskerpage.com
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 616, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 201, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 115, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 98, in get_connection
    conn = self._get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 104, in _get_connection
    return self.create_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 668, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")

2023-09-16 09:49:57,037 ERROR scheduler Exception in Enqueue Events for Site taskerpage.com
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 616, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 201, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 115, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 98, in get_connection
    conn = self._get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 104, in _get_connection
    return self.create_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 668, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")

2023-09-16 09:51:03,069 ERROR scheduler Exception in Enqueue Events for Site taskerpage.com
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 616, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 786, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 201, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 115, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 98, in get_connection
    conn = self._get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 104, in _get_connection
    return self.create_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 668, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")

2023-09-17 19:58:51,299 ERROR scheduler Exception in Enqueue Events for Site taskerpage.com
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/redis/connection.py", line 1198, in get_connection
    if connection.can_read():
  File "env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "env/lib/python3.10/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 303, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "env/lib/python3.10/site-packages/rq/queue.py", line 218, in jobs
    return self.get_jobs()
  File "env/lib/python3.10/site-packages/rq/queue.py", line 207, in get_jobs
    job_ids = self.get_job_ids(offset, length)
  File "env/lib/python3.10/site-packages/rq/queue.py", line 203, in get_job_ids
    self.connection.lrange(self.key, start, end)]
  File "env/lib/python3.10/site-packages/redis/client.py", line 1975, in lrange
    return self.execute_command('LRANGE', name, start, end)
  File "env/lib/python3.10/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "env/lib/python3.10/site-packages/redis/connection.py", line 1202, in get_connection
    connection.connect()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.

